// <auto-generated />
using System;
using KisiRehberProject.DAL.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KisiRehberProject.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230905084215_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KisiRehberProject.DATA.Entities.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdresDetay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("KisiId")
                        .HasColumnType("int");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KisiId");

                    b.ToTable("Adreses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdresDetay = "YeşilYurt",
                            CreateDate = new DateTime(2023, 9, 5, 11, 42, 14, 962, DateTimeKind.Local).AddTicks(6380),
                            Ilce = "Tosya",
                            KisiId = 1,
                            Sehir = "Kastamonu",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AdresDetay = "Karanfil",
                            CreateDate = new DateTime(2023, 9, 5, 11, 42, 14, 962, DateTimeKind.Local).AddTicks(6386),
                            Ilce = "Gölbaşı",
                            KisiId = 1,
                            Sehir = "Ankara",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AdresDetay = "Taşyaka",
                            CreateDate = new DateTime(2023, 9, 5, 11, 42, 14, 962, DateTimeKind.Local).AddTicks(6387),
                            Ilce = "Fethiye",
                            KisiId = 2,
                            Sehir = "Muğla",
                            Status = 0
                        });
                });

            modelBuilder.Entity("KisiRehberProject.DATA.Entities.Kisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Kisis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Sefa",
                            CreateDate = new DateTime(2023, 9, 5, 11, 42, 14, 962, DateTimeKind.Local).AddTicks(5635),
                            Soyad = "Attila",
                            Status = 0,
                            Telefon = "552 828 1903"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ahmet",
                            CreateDate = new DateTime(2023, 9, 5, 11, 42, 14, 962, DateTimeKind.Local).AddTicks(5652),
                            Soyad = "Yılmaz",
                            Status = 0,
                            Telefon = "552 828 1903"
                        });
                });

            modelBuilder.Entity("KisiRehberProject.DATA.Entities.Adres", b =>
                {
                    b.HasOne("KisiRehberProject.DATA.Entities.Kisi", "Kisi")
                        .WithMany("Adresler")
                        .HasForeignKey("KisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisi");
                });

            modelBuilder.Entity("KisiRehberProject.DATA.Entities.Kisi", b =>
                {
                    b.Navigation("Adresler");
                });
#pragma warning restore 612, 618
        }
    }
}
